//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace ESB.Extensions.Resolutions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ESB.Extensions.Schemas.Go")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ESB.Extensions.Schemas.Go", IsNullable=false)]
    public partial class Go {
        
        private string batchIdField;
        
        private string sequenceIdField;
        
        private bool shouldGenerateGoMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BatchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ShouldGenerateGoMsg {
            get {
                return this.shouldGenerateGoMsgField;
            }
            set {
                this.shouldGenerateGoMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ESB.Extensions.Schemas.GoList")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ESB.Extensions.Schemas.GoList", IsNullable=false)]
    public partial class GoList {
        
        private Go[] goField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Go", Namespace="http://ESB.Extensions.Schemas.Go")]
        public Go[] Go {
            get {
                return this.goField;
            }
            set {
                this.goField = value;
            }
        }
    }
}
