//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace ESB.Extensions.Resolutions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/Sql/2008/05/TypedProcedures/dbo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/Sql/2008/05/TypedProcedures/dbo", IsNullable=false)]
    public partial class sp_MergeBatchSequence {
        
        private string batchIdField;
        
        private string sequenceIdField;
        
        private System.Nullable<bool> deterministicSequenceIdsField;
        
        private bool deterministicSequenceIdsFieldSpecified;
        
        private System.Nullable<bool> isFirstSequenceIdField;
        
        private bool isFirstSequenceIdFieldSpecified;
        
        private System.Nullable<int> numberOfMessagesField;
        
        private bool numberOfMessagesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BatchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> DeterministicSequenceIds {
            get {
                return this.deterministicSequenceIdsField;
            }
            set {
                this.deterministicSequenceIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeterministicSequenceIdsSpecified {
            get {
                return this.deterministicSequenceIdsFieldSpecified;
            }
            set {
                this.deterministicSequenceIdsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsFirstSequenceId {
            get {
                return this.isFirstSequenceIdField;
            }
            set {
                this.isFirstSequenceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsFirstSequenceIdSpecified {
            get {
                return this.isFirstSequenceIdFieldSpecified;
            }
            set {
                this.isFirstSequenceIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumberOfMessages {
            get {
                return this.numberOfMessagesField;
            }
            set {
                this.numberOfMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfMessagesSpecified {
            get {
                return this.numberOfMessagesFieldSpecified;
            }
            set {
                this.numberOfMessagesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/Sql/2008/05/TypedProcedures/dbo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/Sql/2008/05/TypedProcedures/dbo", IsNullable=false)]
    public partial class sp_MergeBatchSequenceResponse {
        
        private int returnValueField;
        
        /// <remarks/>
        public int ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
}
