//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace ESB.Extensions.Resolutions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ESB.Extensions.Resolutions.ReceivePipelineServiceResolution")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ESB.Extensions.Resolutions.ReceivePipelineServiceResolution", IsNullable=false)]
    public partial class ReceivePipelineServiceResolution {
        
        private string receivePipelineTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivePipelineTypeName {
            get {
                return this.receivePipelineTypeNameField;
            }
            set {
                this.receivePipelineTypeNameField = value;
            }
        }
    }
}
