//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace ESB.Extensions.Resolutions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ESB.Extensions.Resolutions.SendPipelineServiceResolution")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ESB.Extensions.Resolutions.SendPipelineServiceResolution", IsNullable=false)]
    public partial class SendPipelineServiceResolution {
        
        private string sendPipelineTypeNameField;
        
        private string xLANGMessageComparerTypeNameField;
        
        private int maxMessageCountField;
        
        private SendPipelineServiceResolutionBatchTimeout batchTimeoutField;
        
        private SendPipelineServiceResolutionMessageTimeout messageTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SendPipelineTypeName {
            get {
                return this.sendPipelineTypeNameField;
            }
            set {
                this.sendPipelineTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XLANGMessageComparerTypeName {
            get {
                return this.xLANGMessageComparerTypeNameField;
            }
            set {
                this.xLANGMessageComparerTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MaxMessageCount {
            get {
                return this.maxMessageCountField;
            }
            set {
                this.maxMessageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SendPipelineServiceResolutionBatchTimeout BatchTimeout {
            get {
                return this.batchTimeoutField;
            }
            set {
                this.batchTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SendPipelineServiceResolutionMessageTimeout MessageTimeout {
            get {
                return this.messageTimeoutField;
            }
            set {
                this.messageTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ESB.Extensions.Resolutions.SendPipelineServiceResolution")]
    public partial class SendPipelineServiceResolutionBatchTimeout {
        
        private int daysField;
        
        private bool daysFieldSpecified;
        
        private int hoursField;
        
        private bool hoursFieldSpecified;
        
        private int minutesField;
        
        private bool minutesFieldSpecified;
        
        private int secondsField;
        
        private bool secondsFieldSpecified;
        
        private bool throwExceptionOnTimeoutField;
        
        private bool throwExceptionOnTimeoutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysSpecified {
            get {
                return this.daysFieldSpecified;
            }
            set {
                this.daysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoursSpecified {
            get {
                return this.hoursFieldSpecified;
            }
            set {
                this.hoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinutesSpecified {
            get {
                return this.minutesFieldSpecified;
            }
            set {
                this.minutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondsSpecified {
            get {
                return this.secondsFieldSpecified;
            }
            set {
                this.secondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ThrowExceptionOnTimeout {
            get {
                return this.throwExceptionOnTimeoutField;
            }
            set {
                this.throwExceptionOnTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThrowExceptionOnTimeoutSpecified {
            get {
                return this.throwExceptionOnTimeoutFieldSpecified;
            }
            set {
                this.throwExceptionOnTimeoutFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ESB.Extensions.Resolutions.SendPipelineServiceResolution")]
    public partial class SendPipelineServiceResolutionMessageTimeout {
        
        private int daysField;
        
        private bool daysFieldSpecified;
        
        private int hoursField;
        
        private bool hoursFieldSpecified;
        
        private int minutesField;
        
        private bool minutesFieldSpecified;
        
        private int secondsField;
        
        private bool secondsFieldSpecified;
        
        private bool throwExceptionOnTimeoutField;
        
        private bool throwExceptionOnTimeoutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysSpecified {
            get {
                return this.daysFieldSpecified;
            }
            set {
                this.daysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoursSpecified {
            get {
                return this.hoursFieldSpecified;
            }
            set {
                this.hoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinutesSpecified {
            get {
                return this.minutesFieldSpecified;
            }
            set {
                this.minutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondsSpecified {
            get {
                return this.secondsFieldSpecified;
            }
            set {
                this.secondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ThrowExceptionOnTimeout {
            get {
                return this.throwExceptionOnTimeoutField;
            }
            set {
                this.throwExceptionOnTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThrowExceptionOnTimeoutSpecified {
            get {
                return this.throwExceptionOnTimeoutFieldSpecified;
            }
            set {
                this.throwExceptionOnTimeoutFieldSpecified = value;
            }
        }
    }
}
